[project]
name = 'Decentralized-Adaptive-Sports-Equipment-Sharing'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.athlete-matching]
path = 'contracts/athlete-matching.clar'
clarity_version = 2
epoch = 2.5

[contracts.equipment-registration]
path = 'contracts/equipment-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.event-coordination]
path = 'contracts/event-coordination.clar'
clarity_version = 2
epoch = 2.5

[contracts.modification-tracking]
path = 'contracts/modification-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
